export default {
  // 接口请求baseUrl
  baseUrl: 'http://api.mtd.kfw001.ts',
  // 接口文档地址
  api: {
    // 患者：名医-首页-广告
    patientDocHomeAds: '/Wx/Home/ads',
    // 患者：名医-首页-专家分类
    patientDocHomeCategory: '/Wx/Home/category',
    // 患者：名医-首页-推荐专家
    patientDocHomeExpert: '/Wx/Home/expert',
    // 患者：名医-专家详情
    patientDocElistDetails: '/Wx/Elist/details',
    // 上传患者图片
    apiForImgUpload: 'Wx/Uploadlocal/image',
    // 患者：名医-预约提交信息
    patientDocElistRegister: '/Wx/Elist/register',
    // 患者：名医-获取医导微信二维码
    patientDocElistCode: '/Wx/Elist/code',
    // 患者：孕妇-视频列表-广告
    patientGraVideoAds: '/Wx/Video/ads',
    // 患者：孕妇-视频分类
    patientGraVideoCategory: '/Wx/Video/category',
    // 患者：孕妇-视频列表
    patientGraVideoList: '/Wx/Video/list',
    // 患者：孕妇-视频详情
    patientGraVideoDetails: '/Wx/Video/details',
    // 患者：孕妇-获取题目
    patientGraVideoQuestion: '/Wx/Video/question',
    // 患者：孕妇-保存成绩单
    patientGraVideoSave: '/Wx/Video/save',
    // 患者：个人中心-预约信息
    patientPerOrder: '/Wx/Personal/order',
    // 患者：个人中心-预约信息-预约单
    patientPerDetails: '/Wx/Personal/details',
    // 患者：个人中心-预约信息-保存预约单
    patientPerSave: '/Wx/Personal/save',
    // 患者：个人中心-预约信息-申请支付审核
    patientPerAudit: '/Wx/Personal/audit',
    // 患者：个人中心-就诊记录
    patientPerRecord: '/Wx/Personal/record',
    // 患者：个人中心-药膳记录
    patientPerGoods: '/Wx/Personal/goods',
    // 患者：个人中心-成绩单
    patientPerReport: '/Wx/Personal/report',
    // 患者：药膳列表
    patientGooList: '/Wx/Goods/list',
    // 患者：药膳详情
    patientGooDetails: '/Wx/Goods/details',
    // 患者：保存领取药膳的用户信息
    patientGooSave: '/Wx/Goods/save'
  }
};